version: 0.1
phases:
  install:
    commands:
      - npm install
artifacts:
  type: zip
  files:
    - lambda.js
    - lambda.properties
    - monsanto-table-builder.js
    - package.json
    - '/node_modules/*/**'


