version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm test
 artifacts:
  type: zip
  files:
    - lambda.js
   - lambda.properties
   - monsanto-table-builder.js
   - package.json
   - node_modules/*

   
